{application,myapp,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{myapp_app,[]}},
              {env,[]},
              {modules,[looper,my_bank,myapp_app,myapp_sup,p2,test,u,
                        user_default]}]}.
